vich_uploader:
    db_driver: orm

    metadata: 
        type: attribute

    mappings:
        user_pictures:
            uri_prefix: /assets/images/userPictures
            upload_destination: '%kernel.project_dir%/public/assets/images/userPictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        user_banners:
            uri_prefix: /assets/images/userBanners
            upload_destination: '%kernel.project_dir%/public/assets/images/userBanners'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        
        platform_pictures:
            uri_prefix: /assets/images/platformPictures
            upload_destination: '%kernel.project_dir%/public/assets/images/platformPictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        work_pictures:
            uri_prefix: /assets/images/workPictures
            upload_destination: '%kernel.project_dir%/public/assets/images/workPictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        anime_pictures:
            uri_prefix: /assets/images/animePictures
            upload_destination: '%kernel.project_dir%/public/assets/images/animePictures'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
